name: parallel-cpp
version: 0.3.0
homepage: https://github.com/morloclib/parallel-cpp
synopsis: C++ (std::thread) implementations for the parallel module
description: Thread-pool implementations of the parallel combinators.
category: control
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/parallel-cpp
bug-reports: https://github.com/morloclib/parallel-cpp
